"""Stage: construct one federated threshold-construction cell and publish it atomically.

Threshold construction is deterministic and cheap relative to model training and
scoring, so reuse is verified the same way as the centralized threshold stage: by
recomputing the (pure, side-effect-free) result and comparing its digest against the
published `COMPLETE` marker, rather than deserializing a bespoke schema per result
variant. Score artifacts are never touched, altered, or regenerated by this stage.
"""

from dataclasses import dataclass
from enum import StrEnum
from pathlib import Path
from shutil import rmtree

from datp_core.artifacts.store import AtomicPublication, publish_atomically
from datp_core.domain.enums import ContractSubject, PublicationStatus, StageOperationId
from datp_core.domain.errors import ArtifactIntegrityError
from datp_core.domain.values import Checksum, checksum_file, checksum_text
from datp_core.thresholding.dispatch import ThresholdConstructionRequest, dispatch_federated_threshold
from datp_core.thresholding.models import ThresholdConstructionResult


class ConstructFederatedThresholdsAssetName(StrEnum):
    RESULT = "threshold_result.txt"
    COMPLETE = "COMPLETE"


@dataclass(frozen=True, slots=True)
class ConstructFederatedThresholdsRequest:
    request: ThresholdConstructionRequest
    output_directory: Path
    overwrite: bool


@dataclass(frozen=True, slots=True)
class ConstructFederatedThresholdsResult:
    stage: StageOperationId
    publication_status: PublicationStatus
    result: ThresholdConstructionResult
    complete_digest: Checksum


@dataclass
class _ResultBox:
    """A single-slot mutable box for an `AtomicPublication.write` closure to populate."""

    result: ThresholdConstructionResult | None = None


def threshold_result_checksum(result: ThresholdConstructionResult) -> Checksum:
    return checksum_text(repr(result))


def construct_federated_thresholds_stage(
    stage_request: ConstructFederatedThresholdsRequest,
) -> ConstructFederatedThresholdsResult:
    box = _ResultBox()

    def write(temporary: Path) -> None:
        result = dispatch_federated_threshold(stage_request.request)
        (temporary / ConstructFederatedThresholdsAssetName.RESULT).write_text(repr(result), encoding="utf-8")
        digest = threshold_result_checksum(result)
        (temporary / ConstructFederatedThresholdsAssetName.COMPLETE).write_text(digest.value, encoding="utf-8")
        box.result = result

    reused = publish_atomically(
        AtomicPublication(
            target=stage_request.output_directory,
            overwrite=stage_request.overwrite,
            is_reusable=lambda directory: _is_reusable(directory, stage_request),
            write=write,
            remove_target=rmtree,
        )
    )
    if reused:
        result = dispatch_federated_threshold(stage_request.request)
        status = PublicationStatus.REUSED
    else:
        if box.result is None:
            raise ArtifactIntegrityError(
                "federated threshold write did not populate a result", subject=ContractSubject.THRESHOLD
            )
        result = box.result
        status = PublicationStatus.PUBLISHED
    return ConstructFederatedThresholdsResult(
        stage=StageOperationId.CONSTRUCT_FEDERATED_THRESHOLDS,
        publication_status=status,
        result=result,
        complete_digest=checksum_file(stage_request.output_directory / ConstructFederatedThresholdsAssetName.COMPLETE),
    )


def _is_reusable(directory: Path, stage_request: ConstructFederatedThresholdsRequest) -> bool:
    complete = directory / ConstructFederatedThresholdsAssetName.COMPLETE
    document = directory / ConstructFederatedThresholdsAssetName.RESULT
    if not (complete.is_file() and document.is_file()):
        return False
    result = dispatch_federated_threshold(stage_request.request)
    expected = threshold_result_checksum(result)
    return complete.read_text(encoding="utf-8").strip() == expected.value
