from typing import Final

__all__: list[str] = ["FULL_PARTICIPATION_FRACTION", "FULL_PARTICIPATION_ACCEPT_FAILURES"]

FULL_PARTICIPATION_FRACTION: Final = 1.0
FULL_PARTICIPATION_ACCEPT_FAILURES: Final = False
