from __future__ import annotations

import numpy as np

class kll_doubles_sketch:  # noqa: N801
    def __init__(self, k: int) -> None: ...

    def update(self, array: np.ndarray) -> None: ...

    def serialize(self) -> bytes: ...

    @classmethod
    def deserialize(cls, payload: bytes) -> kll_doubles_sketch: ...

    def merge(self, sketch: kll_doubles_sketch) -> None: ...

    def get_quantile(self, rank: float) -> float: ...

    def normalized_rank_error(self, as_pmf: bool) -> float: ...
