from typing import Any

import numpy as np
from numpy.typing import NDArray

class BaseEstimator: ...

class StandardScaler(BaseEstimator):
    def __init__(self, *, copy: bool = True, with_mean: bool = True, with_std: bool = True) -> None: ...
    def fit(self, X: NDArray[np.float64], y: Any | None = None) -> StandardScaler: ...
    def transform(self, X: NDArray[np.float64], copy: bool | None = None) -> NDArray[np.float64]: ...
    def fit_transform(self, X: NDArray[np.float64], y: Any | None = None, **fit_params: Any) -> NDArray[np.float64]: ...

class MinMaxScaler(BaseEstimator):
    def __init__(
        self, feature_range: tuple[float, float] = (0.0, 1.0), *, copy: bool = True, clip: bool = False
    ) -> None: ...
    def fit(self, X: NDArray[np.float64], y: Any | None = None) -> MinMaxScaler: ...
    def transform(self, X: NDArray[np.float64], copy: bool | None = None) -> NDArray[np.float64]: ...
    def fit_transform(self, X: NDArray[np.float64], y: Any | None = None, **fit_params: Any) -> NDArray[np.float64]: ...
