from enum import StrEnum


class ManifestType(StrEnum):
    DATASET_SOURCE = "dataset_source"
    FEATURE_SCHEMA = "feature_schema"
    CLIENT_PARTITION = "client_partition"
    SPLIT = "split"
    FITTED_PREPROCESSOR = "fitted_preprocessor"
    CHECKPOINT_SELECTION = "checkpoint_selection"
    REGIME_D_FEASIBILITY = "regime_d_feasibility"
    RESOLVED_CONFIGURATION = "resolved_configuration"
    EXPERIMENT = "experiment"
    RESULT_FREEZE = "result_freeze"
    RUN_STATE = "run_state"
    REUSE_LEDGER = "reuse_ledger"
    ARTIFACT_BUNDLE = "artifact_bundle"


class ArtifactType(StrEnum):
    ARTIFACT_BUNDLE = "artifact_bundle"
    RAW_DATASET_REF = "raw_dataset_ref"
    SOURCE_INSPECTION = "source_inspection"
    FEATURE_SCHEMA_MANIFEST = "feature_schema_manifest"
    PARTITION_MANIFEST = "partition_manifest"
    SPLIT_MANIFEST = "split_manifest"
    FITTED_PREPROCESSOR = "fitted_preprocessor"
    PROCESSED_SPLIT = "processed_split"
    SCIENTIFIC_CHECKPOINT = "scientific_checkpoint"
    CHECKPOINT_SELECTION = "checkpoint_selection"
    RECOVERY_CHECKPOINT = "recovery_checkpoint"
    FEASIBILITY_RESULT = "feasibility_result"
    CALIBRATION_SCORE_SET = "calibration_score_set"
    TEST_SCORE_SET = "test_score_set"
    TEMPORAL_SCORE_SET = "temporal_score_set"
    THRESHOLD_OUTPUT = "threshold_output"
    METRIC_OUTPUT = "metric_output"
    RESOURCE_COST_OUTPUT = "resource_cost_output"
    STATISTICAL_OUTPUT = "statistical_output"
    ANCHOR_REPRODUCTION_RESULT = "anchor_reproduction_result"
    RESOLVED_CONFIGURATION = "resolved_configuration"
    DRAFT_EXECUTION_PLAN = "draft_execution_plan"
    FINAL_EXECUTION_PLAN = "final_execution_plan"
    RESULT_FREEZE = "result_freeze"
    TABLE_INPUT = "table_input"
    FIGURE_INPUT = "figure_input"
    RENDERED_TABLE = "rendered_table"
    RENDERED_FIGURE = "rendered_figure"
    WORDING_OUTPUT = "wording_output"
    CODE_STATE = "code_state"
    DEPENDENCY_LOCK_STATE = "dependency_lock_state"
    REUSE_LEDGER = "reuse_ledger"
    RUN_STATE_RECORD = "run_state_record"
    EXPERIMENT_MANIFEST = "experiment_manifest"
