from typing import IO

class Axes:
    def plot(self, *args: object, **kwargs: object) -> None: ...
    def scatter(self, *args: object, **kwargs: object) -> None: ...
    def legend(self) -> None: ...
    def set_xlabel(self, label: str) -> None: ...
    def set_ylabel(self, label: str) -> None: ...

class Figure:
    def subplots(self) -> Axes: ...
    def savefig(self, destination: IO[bytes], *, format: str, metadata: dict[str, str | None]) -> None: ...
