from collections.abc import Callable
from typing import ParamSpec, Protocol, TypeVar

P = ParamSpec("P")
R = TypeVar("R")

class Typer:
    def __init__(self, *, no_args_is_help: bool = ..., help: str | None = ...) -> None: ...
    def add_typer(self, typer_instance: Typer, *, name: str) -> None: ...
    def command(self, name: str) -> Callable[[Callable[P, R]], Callable[P, R]]: ...
    def __call__(self) -> None: ...

class Exit(Exception):
    def __init__(self, code: int | None = ...) -> None: ...

class ArgumentFactory(Protocol):
    def __call__(self, *, case_sensitive: bool = ...) -> object: ...

class OptionFactory(Protocol):
    def __call__(self, *param_decls: str, help: str | None = ...) -> object: ...

Argument: ArgumentFactory
Option: OptionFactory

def echo(message: object, *, err: bool = ...) -> None: ...
