from collections.abc import Iterable, Iterator, Mapping, Sequence
from typing import Any

class ArrowException(Exception): ...
class ArrowInvalid(ArrowException): ...
class DataType: ...

class Field:
    name: str
    type: DataType
    nullable: bool

class Schema:
    names: list[str]
    def __iter__(self) -> Iterator[Field]: ...
    def equals(self, other: Schema, *, check_metadata: bool = ...) -> bool: ...
    def set(self, i: int, field: Field) -> Schema: ...
    def to_string(
        self,
        *,
        truncate_metadata: bool = ...,
        show_field_metadata: bool = ...,
        show_schema_metadata: bool = ...,
    ) -> str: ...

class Table:
    schema: Schema
    def __len__(self) -> int: ...

class Array: ...

def schema(fields: Iterable[Field]) -> Schema: ...
def field(name: str, type: DataType, nullable: bool = ...) -> Field: ...
def float64() -> DataType: ...
def float32() -> DataType: ...
def uint64() -> DataType: ...
def large_string() -> DataType: ...
def bool_() -> DataType: ...
def timestamp(unit: str, tz: str | None = ...) -> DataType: ...
def array(values: Iterable[Any], *, type: DataType | None = ...) -> Array: ...
def table(data: Mapping[str, Array] | Sequence[Array], schema: Schema | None = ...) -> Table: ...
