from collections.abc import Mapping, Sequence
from decimal import Decimal

type ScalarValue = float | int | str | bool | Decimal | None

class Buffer:
    def to_pybytes(self) -> bytes: ...

class BufferOutputStream:
    def getvalue(self) -> Buffer: ...

class BufferReader:
    def __init__(self, data: bytes) -> None: ...

class Schema:
    names: list[str]
    def get_field_index(self, name: str) -> int: ...

class Array:
    def to_pylist(self) -> list[ScalarValue]: ...

class RecordBatch:
    schema: Schema
    num_rows: int
    def column(self, index: int) -> Array: ...
    def serialize(self) -> Buffer: ...
    def slice(self, offset: int, length: int = ...) -> RecordBatch: ...
    def to_pandas(self) -> object: ...

class Table:
    def column(self, index: int) -> Array: ...

def table(data: Mapping[str, Sequence[ScalarValue]]) -> Table: ...
