from pathlib import Path
from types import TracebackType
from typing import Self

from pyarrow import BufferOutputStream, BufferReader, RecordBatch, Schema, Table

def write_table(table: Table, where: Path | BufferOutputStream, *, row_group_size: int | None = ...) -> None: ...
def read_table(where: Path | BufferReader) -> Table: ...

class ParquetWriter:
    def __init__(self, where: Path, schema: Schema) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(
        self,
        exception_type: type[BaseException] | None,
        exception: BaseException | None,
        traceback: TracebackType | None,
    ) -> None: ...
    def write_batch(self, batch: RecordBatch, *, row_group_size: int | None = ...) -> None: ...
    def close(self) -> None: ...
