"""Statistical summaries, inference, mechanisms, and temporal analysis."""

from datp_core.analysis.descriptive import (
    DescriptiveStatistics,
    DescriptiveSummary,
    ObservationCounts,
    QuantileRange,
    count_paired_differences,
    summarize_values,
)
from datp_core.analysis.inference.bootstrap import (
    decide_confirmatory,
    paired_bca_interval,
    supplementary_paired_bca_interval,
    validate_confirmatory_contrasts,
    validate_supplementary_contrasts,
)
from datp_core.analysis.inference.paired import (
    holm_adjust,
    matched_pairs_rank_biserial,
    paired_deltas,
    paired_wilcoxon,
)
from datp_core.analysis.mechanisms import (
    AssociationIssue,
    AssociationObservation,
    AssociationResult,
    AssociationStatistics,
    ClusterPartitionSummary,
    ClusterStabilityResult,
    DivergenceBlocker,
    DivergenceResult,
    GroupDispersionObservation,
    GroupedDispersionResult,
    MechanismEvidence,
    ThresholdMovement,
    ThresholdOperatingPoint,
    blocked_jensen_shannon_divergence,
    cluster_stability,
    decide_model_absorption,
    grouped_dispersion,
    heterogeneity_benefit_association,
    threshold_movement,
)
from datp_core.analysis.models import (
    BcaAdjustment,
    BcaOutcome,
    BcaReason,
    BootstrapInterval,
    CorrelationCoefficient,
    FederatedDesignIdentity,
    MetricSeries,
    MultiplicityDecision,
    MultiplicityPlan,
    MultiplicityResult,
    PairedContrast,
    PairedContrasts,
    PairedDifferenceCounts,
    PValue,
    RankBiserialResult,
    ScientificDecisionResult,
    SupplementaryPairedAnalysisPlan,
    WilcoxonComputationMethod,
    WilcoxonResult,
)
from datp_core.analysis.temporal import (
    TemporalAnalysisRecord,
    TemporalDeploymentProvenance,
    TemporalFutureIdentity,
    TemporalInterpretation,
    TemporalRecoveryResult,
    decide_temporal,
    temporal_analysis_record,
    temporal_recovery,
    validate_frozen_recalibrated_pair,
)
