from typing import Any, Generic, TypeVar

_T = TypeVar("_T")

class AssetSelection:
    @staticmethod
    def assets(*args: Any, **kwargs: Any) -> AssetSelection: ...
    def __or__(self, other: AssetSelection) -> AssetSelection: ...

class ConfigurableResource(Generic[_T]):
    def __init__(self, **kwargs: Any) -> None: ...

class Definitions:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def resolve_job_def(self, name: str) -> Any: ...
    def resolve_all_asset_keys(self) -> Any: ...

def asset(fn: Any = ..., **kwargs: Any) -> Any: ...
def define_asset_job(name: str, selection: Any = None, **kwargs: Any) -> Any: ...
