from pathlib import Path
from typing import Any

import torch

def load_file(filename: str | Path, device: str | int = "cpu", *, backend: str = "mmap") -> dict[str, torch.Tensor]: ...
def save_file(tensors: dict[str, torch.Tensor], filename: str | Path, metadata: dict[str, str] | None = None) -> None: ...
def save(tensors: dict[str, torch.Tensor], metadata: dict[str, str] | None = None) -> bytes: ...
