from datp_core.core.identifiers import AvailabilityStatus, MetricId
from datp_core.core.numeric import MetricValue, Ratio

OPERATING_POINT_METRICS = (
    MetricId.FALSE_POSITIVE_RATE,
    MetricId.FPR_COEFFICIENT_OF_VARIATION,
    MetricId.FPR_SAMPLE_STANDARD_DEVIATION,
    MetricId.FPR_IQR,
    MetricId.FPR_RANGE,
    MetricId.WORST_CLIENT_FPR,
)
OPTIONAL_EQUITY_INDEX_METRICS = (
    MetricId.JAIN_FAIRNESS_INDEX,
    MetricId.GINI_COEFFICIENT,
)
ATTACK_QUALITY_CONTROL_METRICS = (
    MetricId.TRUE_POSITIVE_RATE,
    MetricId.BALANCED_ACCURACY,
    MetricId.BINARY_MACRO_F1,
    MetricId.AUROC,
    MetricId.P10_BINARY_MACRO_F1,
    MetricId.WORST_CLIENT_BALANCED_ACCURACY,
)
ATTACK_SENSITIVE_METRICS = ATTACK_QUALITY_CONTROL_METRICS + (
    MetricId.TPR_COEFFICIENT_OF_VARIATION,
    MetricId.MEAN_CLIENT_MACRO_F1,
    MetricId.POOLED_MACRO_F1,
    MetricId.MEAN_CLIENT_BALANCED_ACCURACY,
)
CONFIRMATORY_METRICS = OPERATING_POINT_METRICS + ATTACK_QUALITY_CONTROL_METRICS
SUPPRESSED_OPERATIONAL_METRICS = (MetricId.ALERTS_PER_DAY,)
CV_ZERO_MEAN_POLICY = AvailabilityStatus.UNDEFINED
NEAR_ZERO_MEAN_FPR_WARNING_CUTOFF = Ratio(0.01)
FIXED_SCORE_QUALITY_CONTROL_INVARIANCE_TOLERANCE = MetricValue(1e-10)
ABSORPTION_REFERENCE_EFFECT_MATERIALITY_CUTOFF = MetricValue(0.01)
