from collections.abc import Sequence
from typing import Any

def adjusted_rand_score(labels_true: Sequence[int], labels_pred: Sequence[int]) -> float: ...
def roc_auc_score(y_true: Any, y_score: Any, **kwargs: Any) -> float: ...
